services:
  instance:
    image: ghcr.io/rairulyle/hoyolab-auto:latest
    restart: on-failure:5
    container_name: hoyolab-auto
    network_mode: bridge
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      TZ: UTC
